behaviors:
  MazeAgentBehavior:
    trainer_type: ppo

    hyperparameters:
      batch_size: 1024          
      buffer_size: 20480
      learning_rate: 5e-4
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 10
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3             
      memory:
        sequence_length: 128
        memory_size: 512
      

    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
        
    behavioral_cloning:
      demo_path: ./Demonstrations
      strength: 0.7                          
      steps: 500000                          
      batch_size: 512                        
      num_epoch: 5                           
      pretrain: true

    max_steps: 80000000
    time_horizon: 2048
    summary_freq: 20000